# settings
set -g default-terminal "tmux-256color"
set -g mouse on
set -g history-limit 10000
set -g base-index 1
set-window-option -g pane-base-index 1
set-window-option -g mode-keys vi

# supposedly this unbreaks things in tmux for vim
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# bindings

## change prefix

# unbind C-b
# set -g prefix C-space

# unbind R

bind R source-file "~/.tmux.conf"

## vim bindings
# unbind h
# unbind j
# unbind k
# unbind l
#
# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R

## split windows
# unbind V
# unbind H

# unbind % # old split vertically
# unbind '"' # old split horizontally

# bind V split-window -h -c "#{pane_current_path}"
# bind H split-window -v -c "#{pane_current_path}"

# make and rename windows
# unbind r # old move to next window
# unbind w # old change current window

# bind r command-prompt -I "#W" "rename-window '%%'"
# bind w new-window -c "#{pane_current_path}"

# switch windows
# bind -n M-j previous-window # using i3 bindings
# bind -n M-\; next-window # using i3 bindings

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavour 'mocha' # latte for light mode

run '~/.tmux/plugins/tpm/tpm'
