return {
  -- base16 colorscheme engine, fed live colors generated by Noctalia
  { "RRethy/base16-nvim", lazy = false, priority = 1000 },
  {
    "LazyVim/LazyVim",
    opts = {
      -- Apply the Noctalia-generated palette. Using the function form so we
      -- call base16's setup() directly (there is no `:colorscheme base16`).
      -- pcall guards the first run before Noctalia has generated matugen.lua.
      colorscheme = function()
        local ok = pcall(function()
          require("matugen").setup()
        end)
        if not ok then
          vim.cmd.colorscheme("tokyonight")
        end
      end,
    },
  },
}
